
export function getWorkScheduleCopy(language) {
  const vi = language === "vi";

  return vi
    ? {
        eyebrow: "Vận hành đội ngũ",
        title: "lịch làm việc.",
        description:
          "Theo dõi ca làm theo ngày hoặc tuần, kéo thả để đổi thời gian và thao tác thuận tiện trên điện thoại.",
        refresh: "Làm mới",
        newShift: "Tạo ca",
        loading: "Đang tải lịch làm việc",
        loadError: "Không tải được lịch làm việc.",
        saveError: "Không lưu được ca làm.",
        deleteError: "Không xóa được ca làm.",
        moveError: "Không thể cập nhật vị trí ca làm.",
        created: "Đã tạo ca làm.",
        updated: "Đã cập nhật ca làm.",
        deleted: "Đã xóa ca làm.",
        moved: "Đã cập nhật ngày và giờ của ca làm.",
        shifts: "Ca làm",
        staff: "Nhân viên",
        hours: "Tổng giờ",
        shortStaffed: "Thiếu người",
        filters: "Nhân viên",
        allEmployees: "Tất cả",
        people: "người",
        searchPlaceholder: "Tìm ca, vị trí hoặc nhân viên...",
        today: "Hôm nay",
        day: "Ngày",
        week: "Tuần",
        previous: "Trước",
        next: "Sau",
        mobileHint:
          "Nhấn giữ ca rồi kéo để đổi giờ. Vuốt vùng trống sang trái hoặc phải để đổi ngày.",
        desktopHint:
          "Kéo ca để đổi giờ hoặc ngày. Kéo thanh dưới cùng để thay đổi thời lượng.",
        unassigned: "Chưa phân công",
        resize: "Thay đổi thời lượng",
        newShiftTitle: "Tạo ca làm mới",
        editShiftTitle: "Chỉnh sửa ca làm",
        shiftTitle: "Tên ca",
        date: "Ngày",
        position: "Vị trí làm việc",
        start: "Bắt đầu",
        end: "Kết thúc",
        requiredStaff: "Số người cần",
        status: "Trạng thái",
        published: "Đã xuất bản",
        draft: "Bản nháp",
        completed: "Hoàn thành",
        cancelled: "Đã hủy",
        assignEmployees: "Phân công nhân viên",
        note: "Ghi chú",
        cancel: "Hủy",
        save: "Lưu ca",
        delete: "Xóa",
        duplicate: "Nhân bản",
        copySuffix: "(bản sao)",
        close: "Đóng",
        confirmDelete: "Bạn chắc chắn muốn xóa ca làm này?",
        invalidDate: "Vui lòng chọn ngày làm việc.",
        invalidTime: "Giờ kết thúc phải sau giờ bắt đầu.",
        invalidRequiredStaff: "Số người cần phải từ 1 trở lên.",
        pending: "Đang lưu...",
        emptyDay: "Chưa có ca làm trong ngày này.",
        clickToCreate: "Chạm vào vùng giờ trống để tạo ca.",
        staffMember: "Nhân viên",
      }
    : {
        eyebrow: "Team operations",
        title: "work schedule.",
        description:
          "Review shifts by day or week, drag to reschedule and work comfortably on mobile devices.",
        refresh: "Refresh",
        newShift: "New shift",
        loading: "Loading work schedule",
        loadError: "Could not load the work schedule.",
        saveError: "Could not save the shift.",
        deleteError: "Could not delete the shift.",
        moveError: "Could not move the shift.",
        created: "Shift created.",
        updated: "Shift updated.",
        deleted: "Shift deleted.",
        moved: "Shift date and time updated.",
        shifts: "Shifts",
        staff: "Staff",
        hours: "Total hours",
        shortStaffed: "Short staffed",
        filters: "Employees",
        allEmployees: "All",
        people: "people",
        searchPlaceholder: "Search shift, position or employee...",
        today: "Today",
        day: "Day",
        week: "Week",
        previous: "Previous",
        next: "Next",
        mobileHint:
          "Press and hold a shift, then drag. Swipe empty space left or right to change day.",
        desktopHint:
          "Drag a shift to change its time or day. Drag the bottom handle to resize.",
        unassigned: "Unassigned",
        resize: "Resize shift",
        newShiftTitle: "Create a new shift",
        editShiftTitle: "Edit shift",
        shiftTitle: "Shift title",
        date: "Date",
        position: "Position",
        start: "Starts",
        end: "Ends",
        requiredStaff: "Required staff",
        status: "Status",
        published: "Published",
        draft: "Draft",
        completed: "Completed",
        cancelled: "Cancelled",
        assignEmployees: "Assign employees",
        note: "Note",
        cancel: "Cancel",
        save: "Save shift",
        delete: "Delete",
        duplicate: "Duplicate",
        copySuffix: "(copy)",
        close: "Close",
        confirmDelete: "Delete this shift?",
        invalidDate: "Select a work date.",
        invalidTime: "End time must be after start time.",
        invalidRequiredStaff: "Required staff must be at least 1.",
        pending: "Saving...",
        emptyDay: "There are no shifts on this day.",
        clickToCreate: "Tap an empty time slot to create one.",
        staffMember: "Staff member",
      };
}
